export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOAD_USERS_LIST_REQUEST = 'LOAD_MOVIES_REQUEST';
export const LOAD_USERS_LIST_SUCCEEDED = 'LOAD_MOVIES_SUCCEEDED';
export const LOAD_USERS_LIST_FAILED = 'LOAD_MOVIES_FAILED';

export const LOAD_REPOS_REQUEST = 'LOAD_REPOS_REQUEST';
export const LOAD_REPOS_SUCCEEDED = 'LOAD_REPOS_SUCCEEDED';
export const LOAD_REPOS_FAILED = 'LOAD_REPOS_FAILED';
